output-format: grouped

strictness: high
test-warnings: false
doc-warnings: false
autodetect: true
member-warnings: false

ignore-paths:
  - docs
  - build
  - tests
  - build.py

pylint:
  options:
    max-line-length: 120
    max-args: 8
    disable:
      - invalid-name
      - no-self-use
